//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCobaLogin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public int userid { get; set; }
        [Display(Name="User Name ")]
        [Required(ErrorMessage = "Username Masih Kosong",AllowEmptyStrings=false)]
        public string username { get; set; }
        [Display(Name="Password ")]
        [Required(ErrorMessage = "Password Belum diisi", AllowEmptyStrings = false)]
        public string userpassword { get; set; }
    }
}
