//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStoreProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DbAnggaEntities : DbContext
    {
        public DbAnggaEntities()
            : base("name=DbAnggaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anak> Anaks { get; set; }
        public DbSet<OrangTua> OrangTuas { get; set; }
    
        public virtual ObjectResult<lihattabeljoin_Result> lihattabeljoin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lihattabeljoin_Result>("lihattabeljoin");
        }
    
        public virtual ObjectResult<ltjparam_Result> ltjparam(Nullable<int> umur)
        {
            var umurParameter = umur.HasValue ?
                new ObjectParameter("umur", umur) :
                new ObjectParameter("umur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ltjparam_Result>("ltjparam", umurParameter);
        }

    }
}
