//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentsDuesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.dues = new HashSet<due>();
            this.People = new HashSet<Person>();
        }
    
        public int HouseID { get; set; }
        public string Block { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<int> emty { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<due> dues { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
