//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentsDuesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PeopleID { get; set; }
        public string IDCard { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> HouseID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual House House { get; set; }
    }
}
