//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapimvc2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahasiswa
    {
        public string MhsId { get; set; }
        public string NamaPertama { get; set; }
        public string NamaTerakhir { get; set; }
        public Nullable<int> umur { get; set; }
        public string jnsk { get; set; }
        public string angkatan { get; set; }
        public string ipk { get; set; }
    }
}
