//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentsDuesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ExpenditureID { get; set; }
        public Nullable<System.DateTime> ExpenditureDate { get; set; }
        public string Expenditure1 { get; set; }
        public Nullable<decimal> Fee { get; set; }
    }
}
