//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentsDuesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeighbourhoodWatch
    {
        public int NeighbourhoodID { get; set; }
        public string Chief { get; set; }
        public Nullable<decimal> Duesdef { get; set; }
        public Nullable<decimal> Cash { get; set; }
    }
}
