//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidentsDuesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResidentsEntities : DbContext
    {
        public ResidentsEntities()
            : base("name=ResidentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<due> dues { get; set; }
        public DbSet<Expenditure> Expenditures { get; set; }
        public DbSet<House> Houses { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<NeighbourhoodWatch> NeighbourhoodWatches { get; set; }
        public DbSet<user> users { get; set; }
    }
}
