//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int creditId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> creditke { get; set; }
        public Nullable<System.DateTime> creditDate { get; set; }
    
        public virtual item item { get; set; }
        public virtual Member Member { get; set; }
    }
}
