//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.credits = new HashSet<credit>();
            this.Trans_M = new HashSet<Trans_M>();
        }
    
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberAdress { get; set; }
        public string Memberphone { get; set; }
    
        public virtual ICollection<credit> credits { get; set; }
        public virtual ICollection<Trans_M> Trans_M { get; set; }
    }
}
