//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicstore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAnggaEntities : DbContext
    {
        public DbAnggaEntities()
            : base("name=DbAnggaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<credit> credits { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Trans_d> Trans_d { get; set; }
        public DbSet<Trans_M> Trans_M { get; set; }
        public DbSet<user> users { get; set; }
    }
}
