//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_M
    {
        public Trans_M()
        {
            this.Trans_d = new HashSet<Trans_d>();
        }
    
        public string TransId { get; set; }
        public Nullable<System.DateTime> TransaDate { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<decimal> TotalTrans { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<Trans_d> Trans_d { get; set; }
    }
}
